Repository HackingThisWorld/medidesk, pull requests merged in 2022-03, with the labels that each got.

#3 Added Prettier Formatting into the Github CICD Actions
  .github/actions/prettier-formatting.yml
Labels: actions, CI/CD

#2 feat: Designing UI, NextAuth Started
  .gitignore
  components/CTA.tsx
  components/Info.tsx
  components/Navbar.tsx
  next.config.js
  package.json
  pages/_app.tsx
  pages/api/auth/[...nextauth].ts
  pages/index.tsx
  prisma/schema.prisma
  styles/globals.css
  yarn.lock
Labels: enhancement

#7 feat(sooditk): User SignIn, Lab Signup/SignIn done
  components/ContactUs.tsx
  components/LabSignIn.tsx
  components/LabSignUp.tsx
  components/Navbar.tsx
  pages/index.tsx
Labels: enhancement

#10 Added License And Readme 🛠🛠
  LICENSE
  README.md
Labels: documentation

#12 Added Service Booking and Colnsultation Form on Services Page
  components/BookModal.tsx
  components/Consultation.tsx
  components/Navbar.tsx
  components/ServiceCard.tsx
  pages/index.tsx
  pages/services.tsx
Labels: enhancement
